[package]
name = "proc_lib_test3"
version = "0.1.0"
edition = "2021"

[dependencies]
quote = "1.0.37"
syn = { version = "2.0.90", features = ["full"] }
proc-macro2 = "1.0.92"

[lib]
proc-macro = true
